let cartData = [
  {
    id: 1,
    title: "Nocco Ice Soda",
    price: 29.99,
    img: "../img/noccoIceSoda.webp",
    quantity: 0,
    link: "../details/detailsID1.html",
  },
  {
    id: 2,
    title: "Nocco Blue Raspberry",
    price: 29.99,
    img: "../img/noccoBlueRas.webp",
    quantity: 0,
    link: "../details/detailsID2.html"
  },
  {
    id: 3,
    title: "Nocco Limon",
    price: 29.99,
    img: "../img/noccoLimon.webp",
    quantity: 0,
  },
  {
    id: 4,
    title: "Nocco Sunny Soda",
    price: 29.99,
    img: "../img/noccoSunnySoda.webp",
    quantity: 0,
  },
  {
    id: 5,
    title: "Nocco Ruby",
    price: 29.99,
    img: "../img/noccoRuby.webp",
    quantity: 0,
  },
  {
    id: 6,
    title: "Nocco Breeze",
    price: 29.99,
    img: "../img/noccoBreeze.webp",
    quantity: 0,
  },
  {
    id: 7,
    title: "Nocco Mango",
    price: 29.99,
    img: "../img/noccoMango.webp",
    quantity: 0,
  },
  {
    id: 8,
    title: "Nocco Blood Orange",
    price: 29.99,
    img: "../img/noccoBloodOrange.webp",
    quantity: 0,
  },
  {
    id: 9,
    title: "Monster Original",
    price: 34.99,
    img: "../img/monsterOriginal.webp",
    quantity: 0,
  },
  {
    id: 10,
    title: "Monster Ultra White",
    price: 34.99,
    img: "../img/monsterUltraWhite.webp",
    quantity: 0,
  },
  {
    id: 11,
    title: "Monster Mango Loco",
    price: 34.99,
    img: "../img/monsterMangoLoco.webp",
    quantity: 0,
  },
  {
    id: 12,
    title: "Monster Monarch",
    price: 34.99,
    img: "../img/monsterMonarch.webp",
    quantity: 0,
  },
  {
    id: 13,
    title: "Monster Aussie Lemonade",
    price: 34.99,
    img: "../img/monsterAussieLemonade.webp",
    quantity: 0,
  },
  {
    id: 14,
    title: "Monster Bad Apple",
    price: 34.99,
    img: "../img/monsterBadApple.webp",
    quantity: 0,
  },
  {
    id: 15,
    title: "Monster Lewis Hamilton",
    price: 34.99,
    img: "../img/monsterLewisHamilton.webp",
    quantity: 0,
  },
  {
    id: 16,
    title: "Monster Pipeline Punch",
    price: 34.99,
    img: "../img/monsterPipelinePunch.webp",
    quantity: 0,
  },
  {
    id: 17,
    title: "Red Bull Original",
    price: 39.99,
    img: "../img/redbullOriginal.webp",
    quantity: 0,
  },
  {
    id: 18,
    title: "Red Bull Sugarfree",
    price: 39.99,
    img: "../img/redbullOriginalSugarfree.webp",
    quantity: 0,
  },
  {
    id: 19,
    title: "Red Bull Blue ed.",
    price: 39.99,
    img: "../img/redbullBlueEdition.webp",
    quantity: 0,
  },
  {
    id: 20,
    title: "Red Bull Pink ed.",
    price: 39.99,
    img: "../img/redbullPinkEdition.webp",
    quantity: 0,
  },
  {
    id: 21,
    title: "Red Bull Purple ed.",
    price: 39.99,
    img: "../img/redbullPurpleEdition.webp",
    quantity: 0,
  },
  {
    id: 22,
    title: "Red Bull White ed.",
    price: 39.99,
    img: "../img/redbullWhiteEdition.webp",
    quantity: 0,
  },
  {
    id: 23,
    title: "Red Bull Apricot ed. ",
    price: 39.99,
    img: "../img/redbullApricotEdition.webp",
    quantity: 0,
  },
  {
    id: 24,
    title: "Red Bull Peach ed.",
    price: 39.99,
    img: "../img/redbullPeachEdition.webp",
    quantity: 0,
  },
];
