let cartData = [
  {
    id: 1,
    title: "Nocco Ice Soda",
    price: 29.99,
    img: "../img/nocco-ice-soda.webp",
    quantity: 0,
    link: "../details/detailsID1.html",
  },
  {
    id: 2,
    title: "Nocco Blue Raspberry",
    price: 29.99,
    img: "../img/nocco-blue-ras.webp",
    quantity: 0,
    link: "../details/detailsID2.html",
  },
  {
    id: 3,
    title: "Nocco Limon",
    price: 29.99,
    img: "../img/nocco-limon.webp",
    quantity: 0,
  },
  {
    id: 4,
    title: "Nocco Sunny Soda",
    price: 29.99,
    img: "../img/nocco-sunny-soda.webp",
    quantity: 0,
  },
  {
    id: 5,
    title: "Nocco Ruby",
    price: 29.99,
    img: "../img/nocco-ruby.webp",
    quantity: 0,
  },
  {
    id: 6,
    title: "Nocco Breeze",
    price: 29.99,
    img: "../img/nocco-breeze.webp",
    quantity: 0,
  },
  {
    id: 7,
    title: "Nocco Mango",
    price: 29.99,
    img: "../img/nocco-mango.webp",
    quantity: 0,
  },
  {
    id: 8,
    title: "Nocco Blood Orange",
    price: 29.99,
    img: "../img/nocco-blood-orange.webp",
    quantity: 0,
  },
  {
    id: 9,
    title: "Monster Original",
    price: 34.99,
    img: "../img/monster-original.webp",
    quantity: 0,
  },
  {
    id: 10,
    title: "Monster Ultra White",
    price: 34.99,
    img: "../img/monster-ultra-white.webp",
    quantity: 0,
  },
  {
    id: 11,
    title: "Monster Mango Loco",
    price: 34.99,
    img: "../img/monster-mango-loco.webp",
    quantity: 0,
  },
  {
    id: 12,
    title: "Monster Monarch",
    price: 34.99,
    img: "../img/monster-monarch.webp",
    quantity: 0,
  },
  {
    id: 13,
    title: "Monster Aussie Lemonade",
    price: 34.99,
    img: "../img/monster-aussie-lemonade.webp",
    quantity: 0,
  },
  {
    id: 14,
    title: "Monster Bad Apple",
    price: 34.99,
    img: "../img/monster-bad-apple.webp",
    quantity: 0,
  },
  {
    id: 15,
    title: "Monster Lewis Hamilton",
    price: 34.99,
    img: "../img/monster-lewis-hamilton.webp",
    quantity: 0,
  },
  {
    id: 16,
    title: "Monster Pipeline Punch",
    price: 34.99,
    img: "../img/monster-pipeline-punch.webp",
    quantity: 0,
  },
  {
    id: 17,
    title: "Red Bull Original",
    price: 39.99,
    img: "../img/redbull-original.webp",
    quantity: 0,
  },
  {
    id: 18,
    title: "Red Bull Sugarfree",
    price: 39.99,
    img: "../img/redbull-original-sugarfree.webp",
    quantity: 0,
  },
  {
    id: 19,
    title: "Red Bull Blue ed.",
    price: 39.99,
    img: "../img/redbull-blue-edition.webp",
    quantity: 0,
  },
  {
    id: 20,
    title: "Red Bull Pink ed.",
    price: 39.99,
    img: "../img/redbull-pink-edition.webp",
    quantity: 0,
  },
  {
    id: 21,
    title: "Red Bull Purple ed.",
    price: 39.99,
    img: "../img/redbull-purple-edition.webp",
    quantity: 0,
  },
  {
    id: 22,
    title: "Red Bull White ed.",
    price: 39.99,
    img: "../img/redbull-white-edition.webp",
    quantity: 0,
  },
  {
    id: 23,
    title: "Red Bull Apricot ed.",
    price: 39.99,
    img: "../img/redbull-apricot-edition.webp",
    quantity: 0,
  },
  {
    id: 24,
    title: "Red Bull Peach ed.",
    price: 39.99,
    img: "../img/redbull-peach-edition.webp",
    quantity: 0,
  },
];
